title: Deola's blogspot
author: Adeola
email: fadeyiadeola1-gmail@.com
description: > # this means to ignore newlines until "baseurl:"
  A marketing website with details in the stock market and asset securities.
theme: minima
# social links
twitter_username: adeola # DO NOT include the @ character, or else the build will fail!
github_username:  adeola # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
